// 
// Code generated by Identity and Access VS Package
// 

function ShowSigninPage(IPs) {
    $.each(IPs, function (i, ip) {
        $("#IPDiv").append('<a href="' + ip.LoginUrl + '"><img class="identity-provider " style="-webkit-user-select: none" src="' + ip.ImageUrl + '" alt="' + ip.Name + '"></a>');
    });
};
