using System.Web.Mvc;

namespace BrainThud.Web.Controllers
{
    public class AccountController : Controller
    {
        // 
        // Code generated by Identity and Access VS Package
        // 
        [AllowAnonymous]
        public ActionResult Login()
        {
            ViewBag.MetaDataScript = "https://brainthud.accesscontrol.windows.net/v2/metadata/identityProviders.js?protocol=wsfederation&realm=http://localhost:36877/&version=1.0&callback=ShowSigninPage";
            return View("~/Views/Account/Login.cshtml");
        }
    }
}
